# Generated by Django 5.1.2 on 2024-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, unique=True)),
                ('positive', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('fake', models.IntegerField(default=0)),
                ('real', models.IntegerField(default=0)),
            ],
        ),
    ]
